[versions]
minecraft = "1.21"
fabric_loader = "0.15.11"
fabric_api = "0.100.7+1.21"
neoforge = "21.0.111-beta"
modmenu = "11.0.1"

# Mixin
fabric_mixin = "0.15.0+mixin.0.8.7"
mixin_extras = "0.4.0"

# Plugins
fabric_loom = "1.7-SNAPSHOT"
publishing = "0.6.2"
neoforge_moddev = "1.0.13"

# Extra Libraries
midnightlib_forge = "1.5.7-neoforge"
midnightlib_fabric = "1.5.7-fabric"
defaultresources = "3.6.0"
dynamicassetgenerator = "6.1.1"
emi = "1.1.10+1.21"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

# Extra Libraries
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
emi_fabric = { module = "dev.emi:emi-fabric", version.ref = "emi" }
emi_neoforge = { module = "dev.emi:emi-neoforge", version.ref = "emi" }
midnightlib_forge = { module = "maven.modrinth:midnightlib", version.ref = "midnightlib_forge" }
midnightlib_fabric = { module = "maven.modrinth:midnightlib", version.ref = "midnightlib_fabric" }

# Default Resources
defaultresources = { module = "dev.lukebemish:defaultresources", version.ref = "defaultresources" }
# Dynamic Asset Generator
dynamicassetgenerator = { module = "dev.lukebemish:dynamicassetgenerator", version.ref = "dynamicassetgenerator" }

# Mixin
fabric_mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "fabric_mixin" }
mixin_extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin_extras" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
publishing = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publishing" }
neoforge_moddev = { id = "net.neoforged.moddev", version.ref = "neoforge_moddev" }
#machete = { id = "io.github.p03w.machete", version.ref = "machete" }