plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

//    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
//    if (at.exists()) {
//        setAccessTransformers(at);
//    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}
repositories {
    maven {
        name = "lukebemish"
        url = 'https://maven.lukebemish.dev/releases/'
    }
}
dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    modImplementation(libs.defaultresources.forge)
    jarJar(libs.defaultresources.forge) {
        capabilities {
            requireCapability("dev.lukebemish:defaultresources-forge")
        }
    }
    modImplementation(libs.dynamicassetgenerator.forge)
    
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}