plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}
sourceSets {
    named("main") {
        resources.srcDir("src/generated/resources")
    }
}
legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}
repositories {
    maven {
        name = "lukebemish"
        url = 'https://maven.lukebemish.dev/releases/'
    }
}
dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly(libs.defaultresources.common)
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.files
}
